import '../styles/globals.css'

import { Box, Flex, Spacer, Button, Link, Text } from '@chakra-ui/react'
import { ChakraProvider } from '@chakra-ui/react'
import Head from 'next/head'

function MyApp({ Component, pageProps }) {
  return (
    <ChakraProvider>
      <Head>
        <title> テロップつくるくん</title>
        <meta name="description" content="Generated by create next app" />
        <link
          href="https://fonts.googleapis.com/earlyaccess/nicomoji.css"
          rel="stylesheet"
        />
      </Head>

      <Flex
        as="header"
        width="full"
        borderBottom={1}
        borderStyle={'solid'}
        align={'center'}
        py={4}
        px={{ base: '20px', md: '100px' }}
        borderColor={'gray.200'}
        bg={'white'}
        color={'gray.600'}
      >
        <Text
          textAlign={{ base: 'center', md: 'left' }}
          fontFamily={'Nico Moji'}
          fontSize={{ base: '2xl', md: 'left' }}
          color={'gray.800'}
        >
          テロップつくるくん
        </Text>
        <Spacer />

        <Link href="https://donate.wikimedia.org/w/index.php?title=Special:LandingPage&country=XX&uselang=ja&utm_medium=sidebar&utm_source=donate&utm_campaign=C13_ja.wikipedia.org">
          <Button colorScheme="blue">寄付する</Button>
        </Link>
      </Flex>
      <Component {...pageProps} />
      <Box
        as="footer"
        role="contentinfo"
        mx="auto"
        maxW="8xl"
        py={10}
        px={{ base: '4', md: '8' }}
      >
        <Text fontSize="sm">
          &copy; {new Date().getFullYear()} なんちゃらかんちゃらシステム開発 ,
          All rights reserved.
        </Text>
      </Box>
    </ChakraProvider>
  )
}

export default MyApp
