import Head from "next/head";

import {
  Box,
  Flex,
  Input,
  Stack,
  Spacer,
  Container,
  Button,
} from "@chakra-ui/react";
import { ChakraProvider } from "@chakra-ui/react";
import React, { useState, useRef } from "react";

export default function Home() {
  return (
    <ChakraProvider>
      <Head>
        <title> テロップつくるくん</title>
        <meta name="description" content="Generated by create next app" />
        <link
          href="https://fonts.googleapis.com/earlyaccess/nicomoji.css"
          rel="stylesheet"
        />
      </Head>

      <Flex
        as="header"
        width="full"
        borderBottom={1}
        borderStyle={"solid"}
        align={"center"}
        py={4}
        px={{ base: "20px", md: "100px" }}
        borderColor={"gray.200"}
        bg={"white"}
        color={"gray.600"}
      >
        <Text
          textAlign={{ base: "center", md: "left" }}
          fontFamily={"Nico Moji"}
          fontSize={{ base: "4xl", md: "left" }}
          color={"gray.800"}
        >
          テロップつくるくん
        </Text>
        <Spacer />

        <Button colorScheme="blue">寄付する</Button>
      </Flex>

      <Container maxW="7xl" pt={{ base: "12", md: "12" }} pb={1} px={4}>
        <Flex
          width="full"
          flexDirection={{ base: "column-reverse", md: "row" }}
        >
          <Stack spacing={4}>
            <Text fontWeight="semibold">コマ画像</Text>
            <input type="file" name="file" id="file" />
            <Text fontWeight="semibold">テロップ</Text>
            <Input inputMode="text" placeholder="どういうお笑い" />
            <Text fontWeight="semibold">ツッコミ</Text>
            <Input inputMode="text" placeholder="どういうお笑い" />
            <Text fontWeight="semibold">番組名</Text>
            <Input inputMode="text" placeholder="相席食堂" />
            <Text fontWeight="semibold">TwitterID</Text>
            <Input inputMode="text" placeholder="@TwitterJP" />
            <Button colorScheme="blue">反映する</Button>
          </Stack>
          <Stack>
            {/* 仮置きでアイドル画像をImgタグで表示しています */}
            <Image
              rounded={"lg"}
              boxSize={{ base: "320px", lg: "500px" }}
              objectFit={"scale-down"}
              src="https://nproduction-japan.com/wp-content/uploads/2021/07/F7D87D49-D860-4FA4-8B79-0C88A06A0366-768x1024.jpeg"
              loading="lazy"
            />
            <canvas id="my-canvas" width="500" height="500" hidden></canvas>
            <canvas id="icon" width="500" height="500" hidden></canvas>
          </Stack>
        </Flex>
      </Container>

      <Box
        as="footer"
        role="contentinfo"
        mx="auto"
        maxW="8xl"
        py={10}
        px={{ base: "4", md: "8" }}
      >
        <Text fontSize="sm">
          &copy; {new Date().getFullYear()} Tanaka without ethics , All rights
          reserved.
        </Text>
      </Box>
    </ChakraProvider>
  );
}
